### ISSUE TITLE
Using <sortname> tag in gamelists to refine sorting order.

### ISSUE THREAD

**Issue by sub-atomic** [fewtarius/351ELEC#106]
In Retropie, you can use `<sortname>` in gamelists so that EmulationStation ignores "The" at the beginning of game titles when sorting alphabetically. Like this:

```
<path>./Legend of Zelda, The (USA) (PRG 0).nes</path>
<name>The Legend of Zelda</name>
<sortname>Legend of Zelda</sortname>
```

The list still shows "The Legend of Zelda," but it sorts it in L instead of in T. This tag can also be used to properly sort series with sequels that use numbers and roman numerals, Pokemon games (use colors instead of numbers), etc.

Is this possible to implement in 351ELEC? Thanks.

**Comment by H3X1C** [comment]
Didn't know this was a feature on retropi, but damn this annoys me more than it should I usually resort to renaming the game.

**Comment by fewtarius** [comment]
I don't expect that we'll consider this due to the amount of work involved.  If someone in the community wanted to take it on, we'd certainly be happy to merge it.
