### ISSUE TITLE
Can't find any networks after installing CFW.  Stock firmware works fine.

### ISSUE THREAD

**Issue by abelogan** [fewtarius/351ELEC#11]
I cannot connect to (or even detect) any wifi networks after installing 351ELEC.  I installed it on a 256 Sandisk microSD card, and everything seems to run fine, except of course anything that you need wifi access to do (scrape, update, etc.)  I know it has something to do with the firmware, because I can put the stock micro SD card into the unit and it connects to my wifi as normal, but if I power down the unit, swap out the mucro SD card for the one with 351 ELEC on it, and try to connect, it doesn't detect any networks, let alone will it connect to any of them.  I tried manually entering the name of my network and the password, but nothing.  

From the main menu, I go to Network Settings and press A.  This brings me to the network settings screen.  The first 2 lines say "NOT CONNECTED".  I press A on "Enable WiFi". The slider to the right of the text moves to the right, turns white, and "WIFI SSID" and "WIFI KEY" show up.  I press A on WIFI SSID.  This takes me to the WIFI SSID screen.  It says "NO WIFI NETWORKS FOUND".  I press A on REFRESH.  It searches for a split second and goes back to the same screen. "NO WIFI NETWORKS FOUND".

I press A on "MANUAL INPUT".  I key in my network name.  I do the same for the password in the WIFI KEY screen and back out to the NETWORK SETTINGS screen.  "NO NETOWRKS FOUND"  still shows up on the Network Settings screen.

I've tried turning Netplay on and off; it doesn't help.

How can I get my device to connect to WiFi using 351 ELEC?

**Comment by fewtarius** [comment]
Again, the issue tracker is not to be used for technical support.  You've neglected to include any information that would help determine which firmware that should be loading such as what WIFI chipset you have, or what version of 351ELEC you're using.
