### ISSUE TITLE
Updating issues, i have problem updating the new version of elec straight from updating menu, it won't update, it wont extract or update anything

### ISSUE THREAD

**Issue by yellowplux** [fewtarius/351ELEC#115]
![20210126_191904](https://user-images.githubusercontent.com/78060991/105933320-717f3180-600b-11eb-8f2a-2fd6b9acd16e.jpg)
![20210126_191904](https://user-images.githubusercontent.com/78060991/105933339-78a63f80-600b-11eb-8b40-3790da1c2050.jpg)

### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

### Device (please complete the following information):
 - Version of 351ELEC that you are using

**Comment by yellowplux** [comment]
I am using nightly update, it seem to do it

I was using stable, it won't

Why?

**Comment by yellowplux** [comment]
This is what it look like when using stable updating 
![Uploading 20210126_193214.jpg…]()

**Comment by yellowplux** [comment]
![20210126_193214](https://user-images.githubusercontent.com/78060991/105934488-8a88e200-600d-11eb-8237-045887fd2273.jpg)

**Comment by johnnyq** [comment]
yes same here not sure

**Comment by fewtarius** [comment]
This is most likely just the internet being the internet.  The updates can take some time to cache.  Try again in a few hours and let us know if it's still an issue.

**Comment by yellowplux** [comment]
Still an issue

**Comment by vdincman** [comment]
Yes, same problem with me, it can not verify the package on stable channel, and when I try it on nighty channel, it begins the procedure but at the very end it says the package is corrupted.

**Comment by yellowplux** [comment]
Yep same here

**Comment by nullstalgia** [comment]
Found a solution. 

Delete the old files from `/storage/.update`

Copy the .tar and .sha into your roms folder. Rename the .tar and .sha to have v before 1.0.9 

Like this:

`351ELEC-RG351P.aarch64-v1.0.9.tar`

And copy them into /storage/.update with File Manager or an ssh terminal. (DO NOT DO IT WITH THE SD CARD IN YOUR PC! DO IT FROM THE DEVICE)

Run update like you would normally from the menu.

:)

**Comment by yellowplux** [comment]
It said it failed, not updating, I follow exactly what you said

**Comment by nullstalgia** [comment]
@yellowplux 

Did you also delete `update.log` ?

If so, try this:

Attempt the update normally, let it fail.

Follow the guide normally, but leave `update.log` in `.update`

And if possible, can you send a screenshot of the files in there?

**Comment by yellowplux** [comment]
> @yellowplux
> 
> Did you also delete `update.log` ?
> 
> If so, try this:
> 
> Attempt the update normally, let it fail.
> 
> Follow the guide normally, but leave `update.log` in `.update`
> 
> And if possible, can you send a screenshot of the files in there?

![Uploading 20210127_022449.jpg…]()

**Comment by yellowplux** [comment]
![Uploading 20210127_022449.jpg…]()

**Comment by nullstalgia** [comment]
Try uploading to https://imgur.com/upload or a similar service :)

**Comment by yellowplux** [comment]
![Uploading 20210127_022449.jpg…]()

**Comment by yellowplux** [comment]
https://ibb.co/fDKcLcy

**Comment by nullstalgia** [comment]
What are the sizes of each of the files? You can just type it out, no need for a screenshot :)

**Comment by yellowplux** [comment]
Both are 9

**Comment by nullstalgia** [comment]
Yep, there it is again. Make sure to download the .tar and .sha256 from your PC, then put them into the ROMs folder

**Comment by fewtarius** [comment]
Looks like there was a typo in the 1.0.9 tag that caused a file not found error.  It has been corrected.
