### ISSUE TITLE
EmulationStation not displaying game name from Gamelist.xml "name" property

### ISSUE THREAD

**Issue by anthonycaccese** [fewtarius/351ELEC#12]
### Describe the bug
After scraping metadata for a system and updating game lists the name of the game displayed in EmulationStation still displays as the filename of the game instead of the value from the "name" property in gamelist.xml.  I have tested and seen this behavior using the themes Alekfull-Solo-Horizontal, ES-Theme-EmuElecCarbon and one my own themes [ES-Theme-Artbook-3-2](https://github.com/anthonycaccese/es-theme-art-book-3-2)

### To Reproduce
1. Using any of the themes listed above
2. Scrape a system using the "Scrape" option from the Main Menu (in my case I am testing with GBA)
3. Scrape from Screenscraper with standard settings
3. Allow scraper to finish
4. Open Main Menu again and go to "Games Settings" > "Update Games Lists"
5. View the gamelist.xml for the system scraped compared to what displays on screen and check that expected properties are displayed

### Expected behavior
The name listed for a game in EmulationStation is expected to match the name property for that game in gamelist.xml

### Screenshots
![IMG_8734](https://user-images.githubusercontent.com/1454947/99301550-23380000-281c-11eb-92b5-d021e045943c.JPG)
![IMG_8732](https://user-images.githubusercontent.com/1454947/99301535-1d421f00-281c-11eb-9920-ae9264ece55b.JPG)

### Device (please complete the following information):
Version 1.0.1 of 351ELEC
![IMG_8735](https://user-images.githubusercontent.com/1454947/99301837-8a55b480-281c-11eb-980e-3c88a0dfef1c.JPG)

### Additional context
Attached is the gamelist XML I have for my GBA system for reference ([gamelist.xml.zip](https://github.com/fewtarius/351ELEC/files/5549376/gamelist.xml.zip))

I figure there may be something simple I am missing so I am still looking on my end but just in case I thought I should submit this.  

Thank you for all of your work on 351Elec, I am really enjoying how simple and clean it is.

**Comment by fewtarius** [comment]
This is the default because it's my personal preference.  It can be disabled with

UI Settings -> Show Filenames in Lists -> Disable.

**Comment by anthonycaccese** [comment]
nice! I'm sorry for missing that and thank you for your response.  Closing this out.
