### ISSUE TITLE
Defaut Root Password not working

### ISSUE THREAD

**Issue by Burtonnak** [fewtarius/351ELEC#121]
On MacOS, SSH with terminal tools :
1- Enable Wifi
2- Get IP address
3- Enable SSH
4- Command line : ssh root@<youripaddress>
5- Accept keyhost prompt : yes
6- Enter root password : 351elec
        => roo@192.168.1.61's password: 
        Permission denied, please try again.

**Comment by fewtarius** [comment]
Please use templates for bug reports/feature requests and discord for support.
