### ISSUE TITLE
Nintendo DS Emulation Don't Work after upgrade

### ISSUE THREAD

**Issue by Burtonnak** [fewtarius/351ELEC#122]
Previous version 1.0.8
Launch a nds game => OK (after drastic installation throw wifi)

Upgrade to version 1.0.9 via wifi.
Once the version is installed, try to launch a nds game => KO

With uppate interface throw wifi connexion :
Uninstall drastic software, reboot
Install Drastic Software, reboot, check installation statu on updgrade interface => OK

try to launch a nds game => KO

**Comment by fewtarius** [comment]
Please use discord for support.
