### ISSUE TITLE
Scraping doesn't work for filenames beginning with numbers

### ISSUE THREAD

**Issue by cyperium** [fewtarius/351ELEC#123]
### Describe the bug
Files beginning with a number doesn't get scraped even though it is a valid game. I suppose that the filename doesn't have to be exact for the scraping to work so something else might be going on.

I'm not sure if this is a invalid behavior of 351ELEC or if it is a invalid behavior of screenscraper.fr, but even if it is a fault of screenscraper.fr the information sent to them could be modified to take away beginning numbers.

### To Reproduce
Have a game with a filename beginning with a number.

### Expected behavior
The game gets scraped.

### Device (please complete the following information):
rg351p with 351ELEC version 1.0.9

**Comment by fewtarius** [comment]
Remove the number prefixes from the games, they're not a natural part of the filename.
