### ISSUE TITLE
[THEME ADD REQUEST] AlekFull-Solo-Horizontal-Xargons-ED

### ISSUE THREAD

**Issue by XargonWan** [fewtarius/351ELEC#14]
Feel free to include my edit to the RG351P default theme in the next releases:
https://github.com/XargonWan/AlekFull-Solo-Horizontal-Xargons-ED

**Comment by fewtarius** [comment]
There's no need to wait for a release, we can update the theme metadata any time now.  I'll review and add it.

**Comment by fewtarius** [comment]
Added, thanks!
