### ISSUE TITLE
The system continues to operate at 1.3 GHz

### ISSUE THREAD

**Issue by ToniBC** [fewtarius/351ELEC#2]
Hello, I don't know if it is a bug, but as a feature it says that it supports 1.5 GHz with the Ambernic patch but that is not reflected anywhere and the performance is the same in everything, so that does not activate or it does not work.

If you activate from any option? Speed could be displayed in system menu.

**Comment by fewtarius** [comment]
Closing - be sure to use the templates.  The device runs at 1.5GHz on demand, with PSP and Dreamcast running at that speed at all times beginning with the next update.
