### ISSUE TITLE
OpenBOR controls issue

### ISSUE THREAD

**Issue by XargonWan** [fewtarius/351ELEC#20]
### Describe the bug
OpenBOR controls are completely messed up, for example start and select are mapped as up and down making the games unplayable.

### To Reproduce
1. Go to OpenBOR system.
2. Start any game.
3. Try to play with messed controls.

### Expected behavior
The buttons are working correctly, I am not sure which of XABY is 1234.

### Device (please complete the following information):
 - Version of 351ELEC 10.2 32bit

**Comment by fewtarius** [comment]
Controls are fixed in 1.0.3.
