### ISSUE TITLE
Global Saves Folder

### ISSUE THREAD

**Issue by XargonWan** [fewtarius/351ELEC#22]
### Is your feature request related to a problem? Please describe.
Creating a global save folder for saves and save states in order to easly backup them (or to sync them between compatible devices).

### Describe the solution you'd like
Move the retroarch saves into /roms/saves (so on the readable games partition) globally.
Configure standalone emulators to save there if possible, if not just symlinking their save folders into /roms/saves.

### Describe alternatives you've considered
Don't do it because we will lose the standard folder structure for emulationstation based devices but implement a "backup saves" script into the system that will copy all the saves in the said directory (/roms/saves).

**Comment by fewtarius** [comment]
This is already on the long term tracker.
