### ISSUE TITLE
EmulationStation default audio settings + fix

### ISSUE THREAD

**Issue by XargonWan** [fewtarius/351ELEC#23]
### Is your feature request related to a problem? Please describe.
Change the default audio settings.

### Describe the solution you'd like
START -> Sound Settings put the following as defaults:
- Show Overlay when volume changes (ON) //**NB: this function is not working now.**
- Lower music when playing videos (ON)
- Enable navigation sounds (ON)
- Enable video audio (ON)

**Comment by fewtarius** [comment]
This is a great idea, but I don't think we'll add it as the logic required is significant.
