### ISSUE TITLE
PPSSPP Broken in 1.0.3 RC1

### ISSUE THREAD

**Issue by XargonWan** [fewtarius/351ELEC#24]
### Describe the bug
PSPP too big menu graphics and not fluid controls, cannot load my savestates but from the sounds that is making I may be able to load the actual save (no state), however after the intro the screen remains black.
The black game issue seems to be happen only with FFT as KH is working correctly.
However the emulator menu issue is common for all the games.

### To Reproduce
1. Start any PSP game.
2. Press the two joysticks to enter the menu.
3. Scrolling down to the main menu brings you to the states menu.
4. From the states menu I didn't find any way to return to the main menu.

### Expected behavior
- Smaller menu and possibility to navigate on the right side to reach the man menu from the states menu.
- FFT was working in the previous versions.

### Screenshots
Maybe a video is more clear: https://streamable.com/zqiupe

### Device (please complete the following information):
 - 1.0.3 64 bit

### Additional context
Update by replacing the said files and not reflashing.

**Comment by fewtarius** [comment]
This was explained in #17.   Won't fix.
