### ISSUE TITLE
Auto Lock when inactive

### ISSUE THREAD

**Issue by XargonWan** [fewtarius/351ELEC#25]
### Is your feature request related to a problem? Please describe.
More battery saving if someone is leaving the device without manually locking it.

### Describe the solution you'd like
After X seconds (maybe the user can set them in the menu), I would say 5 minutes by default, the system is doing the same function as the user is pressing the power button once: going into standby.

### Describe alternatives you've considered
Manually lock the screen.

### Additional context
As already discussed on Discord this option may consume more memory if a new systemd is created, however the system (I don't know in which point) has the ability to start a screensaver, so we got a sort of timer already that we may use.
However I don't know what happens to this function when the emulator is called.

**Comment by fewtarius** [comment]
I think the issue we will run into is that people will not realize it's sleeping and power it off/reset it which may corrupt things.  It wouldn't be very difficult to implement through the ES screensaver functions, but I don't think we'll implement this one.
