### ISSUE TITLE
Video screensaver showing bezels

### ISSUE THREAD

**Issue by XargonWan** [fewtarius/351ELEC#26]
### Describe the bug
When the video screensaver starts it shows random bezels on top of the videos.

### To Reproduce
1. Set screen saver as random video inside the UI configs.
2. Click on SELECT
3. LAUNCH SCREENSAVER

### Expected behavior
The video should start without any issue.

### Screenshots
Video: https://streamable.com/o0iiwt

### Device (please complete the following information):
 - 351ELEC 1.0.3 RC1 64bit

### Additional context
Broken even in the previous version.

**Comment by fewtarius** [comment]
I'm unable to recreate this on my handheld with my normal daily config or a fresh flash.  It may be something local to your configuration.
