### ISSUE TITLE
Where to find the 351Elec logo for theme creators?

### ISSUE THREAD

**Issue by nicosensei** [fewtarius/351ELEC#35]
Hi,

I have a couple themes I made for EmuElec on the Ordoird Go Advance, that I'd like to move over to 351Elec / RG351P. Basically the only modification I'd do would be replacing the EmuElec logo by the RG551 logo, but I can't find it anywhere...

The image displayed on boot would do, but as far as I know it's a base64 encoded image in the kernel image itself.

Good job on this distro!

**Comment by fewtarius** [comment]
Thank you!  The logos can be found here: https://github.com/fewtarius/351ELEC/tree/main/distributions/351ELEC/splash

**Comment by nicosensei** [comment]
Great! Many thanks!

**Comment by fewtarius** [comment]
> Great! Many thanks!

No problem!  Send me the repos of your themes and I'll add them to the theme list. :)
