### ISSUE TITLE
Instructions to get ports to work

### ISSUE THREAD

**Issue by nicosensei** [fewtarius/351ELEC#36]
Hi,

Currently I'm a bit clueless as to how to get ports to work. It seems that files should be put in the time/ports subfolders I bathe STORAGE partition? Or the GAMES partition?

I can get Cannonball and Cave Story to run, but no luck with Reminiscence, Doom 1&2 so far...

**Comment by fewtarius** [comment]
The issue tracker isn't for technical support, try discord.
