### ISSUE TITLE
Can't turn off RGA scaling

### ISSUE THREAD

**Issue by Yeekoi** [fewtarius/351ELEC#38]
### Describe the bug
I turned RGA scaling on for NES games because I think it looks better than integer scaling, but now it's turned on in every game, whether it's NES, GBA or SNES. When I turn the option off, it corrects the problem while I'm playing the game, but as soon as I leave the game and start another one from inside EmulationStation, RGA scaling is turned back on. So it won't stay off.

### To Reproduce
1. Go to the RetroArch menu.
2. Navigate out of the quick menu and go to the next menu to the right, then navigate down to the video options.
3. Navigate down and turn on RGA scaling.

### Expected behavior
I expect that when I turn off RGA scaling in the RetroArch menu, that it stays off and doesn't turn back on every single time I want to play another game.

### Device:
 - RG351P on version 1.0.4 of 351ELEC

**Comment by fewtarius** [comment]
1.0.4 defaults consoles to RGA scaling, and handhelds to integer scaling.  This is by design.  To disable it, you would need to enable override saves under User Interface -> Menu Item Visibility -> Quick Menu -> Show Save Core Overrides, disable RGA scaling, and then save a new override.
