### ISSUE TITLE
SNES Display Ratio

### ISSUE THREAD

**Issue by akhobbes** [fewtarius/351ELEC#41]
Trying to keep games stretched to 16:9 or 3:2 full screen but retroarch defaults to 8:7 no matter what. I've tried changing global settings and creating/saving new retroarch cfg but nothing sticks. It's SO annoying. This was fine on global settings on previous versions, now it seems broken :(

**Comment by fewtarius** [comment]
Duplicate of #38.

**Comment by akhobbes** [comment]
I disabled RGA scaling, still won't default to 16:9 or 3:2 on SNES. I noticed it won't save the retro cfg file.
