### ISSUE TITLE
More Scaling/Video Options in EmulationStation

### ISSUE THREAD

**Issue by myReaper** [fewtarius/351ELEC#43]
### Is your feature request related to a problem? Please describe.
RGA Scaling and Bilinear Filtering should be added to the EmulationStation settings per System.

Mostly out of convenience but its also interesting for users new to RG351P as there are guidess (for example https://retrogamecorps.com/2020/10/24/rg351p-screen-configuration-guide/ ) telling users to modify these settings.

### Describe the solution you'd like
Add RGA Scaling and Bilinear Filtering options to EmulationStation Settings -> Game Settings and Game Settings - per System Advanced Configuration

### Describe alternatives you've considered
Its possible to change these settings directly in RetroArch but as integer scaling is also in the emulationstation menu it would be good to have these two options also there.

### Additional context
-

**Comment by fewtarius** [comment]
Please use the templates to open feature requests.

**Comment by myReaper** [comment]
Updated

**Comment by myReaper** [comment]
Another update:
The "Billinear Filtering" option in the RetroArch seems to be called **video_smooth = "true"** in the config file and there is an option "Smooth Games" in EmulationStation which probably are all the same. Maybe its an option to simply rename the option in EmulationStation "Smooth Games / Bilinear Filtering"  (like both names) to avoid any confusion.

**Comment by fewtarius** [comment]
This is finished, and will be available in tonight's nightly build.
