### ISSUE TITLE
Please upstream changes

### ISSUE THREAD

**Issue by TheLastProject** [fewtarius/351ELEC#45]
Hey 351ELEC!

It's cool to see that even though EmuELEC doesn't want to support the Anbernic RG351P you are finding the EmuELEC source code useful for your project.

I have just one request though. I noticed you have been improving a lot of things, of which some things aren't specific to the RG351P. Could you please consider making pull requests to EmuELEC when you improve something that's not just for RG351P? That way all users of EmuELEC-supported devices can enjoy your improvements too.

Thank you for considering!

**Comment by fewtarius** [comment]
There are a few things that I would like to upstream when I have some time. :)
