### ISSUE TITLE
OpenTyrian Port doesn't start

### ISSUE THREAD

**Issue by vbuciov** [fewtarius/351ELEC#48]
### Describe the bug
rather than start the game goes to a log black screen

### To Reproduce
Go to 'Ports'
Click on 'OpenTyrian'
something it seems like an error comes out

### Expected behavior
The game should start.

### Screenshots
I think it's self explanatory

### Device (please complete the following information):
 - 351ELEC 1.0.4 at 2020-12-14

### Additional context
The data file is correctly placed in the correct folder, and actually you can make it works by editing the script of this game 

Opentyrian.sh
${PORT} -t /storage/roms/ports/opentyrian >> $EE_LOG 2>&1 for ${PORT} -t /storage/roms/ports/opentyrian >&1

but for some reason  it goes back to normal once you restart the console.

I noticed you fixed this same issue for Diablo, so I think you should do same thing for this game. As far as I know it's all about to go to packages/games/ports/sources/ports.yaml then find the OpenTyrian section and add following lines:

  commands:
    - '## on "Amlogic" project we need to remove asound.conf or else OpenTyrian will have no sound.'
    - '[[ "$EE_DEVICE" == "Amlogic" ]] && mv /storage/.config/asound.conf /storage/.config/asound2.conf'
    - LOG_FILE=/storage/roms/ports/opentyrian/log.txt
    - ${PORT} -t /storage/roms/ports/opentyrian >> $LOG_FILE 2>&1
  commands_end:
    - '[[ "$EE_DEVICE" == "Amlogic" ]] && mv /storage/.config/asound2.conf /storage/.config/asound.conf'

**Comment by fewtarius** [comment]
This should be fixed in the next nightly build, let me know if it's still an issue.
