### ISSUE TITLE
Star Wars Episode 1: Racer don't work well. N64 & Dreamcast versions.

### ISSUE THREAD

**Issue by Zlitus** [fewtarius/351ELEC#49]
### Describe the bug
Hello, I'm trying with every OS available on the RG351P to launch Star Wars Episode 1: Racer, on N64 or on Dreamcast. On N64, it launch and we can play, but we see only the bottom-half of the screen in game, like if the camera was too high compare to it original position.
On Dreamcast, we can launch the game but it is very laggy and it freeze on the menu before to reach the track.

### Device:
I'm using 315ELEC 1.0.4

**Comment by Zlitus** [comment]
I found a solution by using the RetroArch options and by using another emulator for the N64 version. The problem is still there for the Dreamcast version, I'll do more investigations tomorrow

**Comment by fewtarius** [comment]
You'll find that a lot of N64 and Dreamcast games don't play well on this handheld, as they require a higher spec for emulation.
