### ISSUE TITLE
Remove all "auto" hotkeys

### ISSUE THREAD

**Issue by myReaper** [fewtarius/351ELEC#50]
### Is your feature request related to a problem? Please describe.
There are specific hotkey's configured as "Auto" in RetroArch which can't be unset via RetroArch (e.g. you currently need to manually configure a non-existing key via config file to unbind them).

### Describe the solution you'd like
Remove all the "Auto" hotkeys (e.g. the source of why they are configured as auto).

### Describe alternatives you've considered
Alternative is to manually change config file settings.

### Additional context
In RetroArch there are some Hotkey's configured as "Auto". For example, the Volume Up/Down or Save State+/-. These Hotkeys have a different source than the retroarch config file. Right now, the Volume up/down hotkey for example is per default configured to "nul" in the retroarch.cfg which should unbind the hotkey. However, as the hotkey has any "Auto" setting (maybe inherited from EmulationStation or any Controller Config file?) its not possible to completely unbind the hotkey within RetroArch. 

I think the best solution would be to remove the source of these Auto hotkey's so they will not have a default bind and can get unset.

For example, the volume up/down is pretty useless in my opinion as it just goes from 100% to 300% instantly and we have a hardware button for Volume anyway.

**Comment by fewtarius** [comment]
This should be completed in a nightly as we've adopted new retroarch defaults.
