### ISSUE TITLE
controllers not working for megamen x3 and x4

### ISSUE THREAD

**Issue by bubunuh** [fewtarius/351ELEC#53]
### Describe the bug
None of the buttons are working in these two games

### To Reproduce
Use PCSX emulator and check these games.

### Device (please complete the following information):
 - 351ELEC 1.0.4 for rg351p

**Comment by fewtarius** [comment]
This is covered in the wiki: https://github.com/fewtarius/351ELEC/wiki/Getting-to-Know-351ELEC#playstation-default-controls
