### ISSUE TITLE
Screensaver

### ISSUE THREAD

**Issue by brnl** [fewtarius/351ELEC#57]
I just found out the hard way that the RG351P's screen is prone to 'burn in' really easily. I've let my device stand on the favorites screen for a while and now these pixels are a bit dimmer than the rest, which means the word 'Favorites' is now always visible in games and other screens, especially on a dark background.

This makes me thinking that a screen saver would be a really good feature in the EmulationStation. Or just a auto-standby. Just dimming doesn't seem to be enough for that.

_PS: The power saving modes could use some more descriptive names too. What does 'enhanced' and 'instant' mean? ;-)_

**Comment by fewtarius** [comment]
We have a screensaver in EmulationStation.  Set your screensaver to 'black' and it will blank the screen.

The power saving modes are EmulationStation specific and their function is very confusing.  I plan to set a default in the code and just remove it from the menu as it's not really useful.
