### ISSUE TITLE
Emulationstation - Rewind options does nothing

### ISSUE THREAD

**Issue by XargonWan** [fewtarius/351ELEC#61]
### Describe the bug
The rewind option is not passed to RetroArch by EmulationStation.

### To Reproduce
1. Enter the desired system in Emulationstation
2. Press select
3. Go to advanced system options
4. Change the rewind option from auto to on

### Expected behavior
The rewind option should be enabled in RetroArch but when the game is running, if I open retroarch and I go to frame throttle menu, the rewind option is not enabled.  
Once enabled it will work as supposed with the correct hotkeys until next restart of retroarch.

### Device (please complete the following information):
v1.0.6 - Release Candidate 1

### Additional context
Maybe we can think to auto enable the rewind feature for all the retroarch cores that are not suffering for it (like low end emulators).

**Comment by XargonWan** [comment]
I tested it only on sega megadrive default core.

**Comment by XargonWan** [comment]
Update: seems like in the SNES default core not only the rewind option from ES is not going to RA but even the **shader set** configuration.

**Comment by XargonWan** [comment]
Updated with a summary of which system is broken where.

**Comment by fewtarius** [comment]
This will be fixed in the nightly, and in the next RC.
