### ISSUE TITLE
Unable to connect wifi when the password with $ sign

### ISSUE THREAD

**Issue by chinjw** [fewtarius/351ELEC#63]
### Describe the bug
I try to connect the to my WIFI, but i found that it won't connect to the WIFI if my password with $ sign. 
Once i reset my password to something else without $ sign, it connect as expected.

### To Reproduce
Just make sure your WIFI password with $ sign , then you'll notice that nothing happen after you enable & keyin all the necessary info.

### Expected behavior
Should connect with password with $ sign

### Device (please complete the following information):
 - Version of 351ELEC = 1.0.5

### Additional context
-

**Comment by fewtarius** [comment]
This is an issue upstream as well.  The current solution is to use a passphrase without a $, or to set it manually in .config/emuelec/configs/emuelec.conf then change the passphrase on your device.  Correcting it properly will take significant effort making this a won't do.
