### ISSUE TITLE
Nintendo DS (Drastic) Installation on SD card

### ISSUE THREAD

**Issue by cyperium** [fewtarius/351ELEC#66]
Could you develop a way to install Drastic without having to use WiFi? I wasn't planning on purchasing an adapter and the only reason would be to play DS games using Drastic. There's probably a good reason why this limit is present but I don't understand why.

### Describe the solution you'd like
Ability to install Drastic without having to use WiFi.

### Describe alternatives you've considered
I have considered if it is possible to install a different DS emulator myself, the best would be to be able to install Drastic though as it seems to be the best. One alternative could be to make a step-by-step guide to install it on the SD if it is deemed to complicated to do, why not make it pre-installed?

**Comment by fewtarius** [comment]
Unfortunately Drastic's current licensing does not allow us to distribute it on our media.  If there are other DS emulators they will be considered.
