### ISSUE TITLE
NTFS support lost in 1.0.6

### ISSUE THREAD

**Issue by denisvmedia** [fewtarius/351ELEC#67]
I used to use an NTFS usb flash with additional disk space on it, but now as I can see NTFS support is removed from the new firmware. Could we have it back in the future fw versions, please?

**Comment by fewtarius** [comment]
Sure thing, I didn't think anyone was using it.

**Comment by fewtarius** [comment]
This is fixed in the repo and will be in our nightly build tonight if you don't want to wait for 1.0.7.
