### ISSUE TITLE
Feature Request: EXT4 Games Partition Support Option

### ISSUE THREAD

**Issue by johnnyq** [fewtarius/351ELEC#69]
This would allow better performance and wayy better stability than FAT32. 
I know the access would be limited for Windows and MacOS users without installing third party tools to access the ext4 partition, but there is the choice of using SSH to transfer ROMs via WiFi

Another solution would be to have two images
a FAT32 games partition image and ext4 games partition image.

**Comment by fewtarius** [comment]
I agree that ext4 would be more stable and possibly a better performing solution, but we've chosen to support the wider audience and embraced FAT32.  We recently evaluated EXFAT, but with kernel 4.4 it requires FUSE and suffers from all sorts of performance problems.  We may re-evaluate if we are able to move up to 5.9, but for now I don't believe we'll make another change.

Now that we support updating over WIFI, you are free to remove the FAT32 partition yourself and expand the storage partition.  The updates should continue to work fine, and as long as you don't reflash I don't see any reason it would break.
