### ISSUE TITLE
smdb service not found

### ISSUE THREAD

**Issue by ireyagun** [fewtarius/351ELEC#75]
### Describe the bug
smdb daemon not found

### To Reproduce
1. open ssh conection
2. try to start smbd:  systemctl start smbd
3. see the error: Failed to start smbd.service: Unit smbd.service not found

### Expected behavior
Start service smbd

### Device (please complete the following information):
 version 1.0.6

**Comment by fewtarius** [comment]
This is not a bug, smb is intentionally disabled to preserve memory.
