### ISSUE TITLE
ScreenScraper Quota Error Message

### ISSUE THREAD

**Issue by xmassound** [fewtarius/351ELEC#78]
I'm having ScreenScraper issue. I'm registered and a patreon supporter with 50000 scrape quota per day but I get maximum quota error message at 10006 scrape. (less than free user 20000). My guess is that whether you are free or patreon user, even without login/pass, you get 10000 maximum per day. I tried without login and password and it works (when it resets at 3pm Pacific Time). Please fix this so patreon user can use full benefit and also REGISTERED user can use maximum 20000 quota. Also, I have 2 threads but only 1 thread is working.

### Device (please complete the following information):
 - Version 1.0.7

**Comment by fewtarius** [comment]
Taking a quick look at what it would take to correct, this isn't something that I'll spend time on, as it may require significant amount of effort that's better spent elsewhere.
