### ISSUE TITLE
Scraped videos don't play at all

### ISSUE THREAD

**Issue by MonsieurDaz** [fewtarius/351ELEC#8]
### BUG
The scraped videos do not play anymore, no matter which theme you're using. The issue is found in all gamelists (the screenshots won't get replaced with the scraped videos), but also on any system's screen if you select the "random video"/"mini random video" (the background will remain black).

### To Reproduce

- Gamelist: Just go into a gamelist.
- Systemview**: Select the Carbon theme, then go to UI Settings --> theme configuration --> background, and select "random video" or "random mini video".

### Screenshots
![image](https://user-images.githubusercontent.com/34653853/99190141-28864380-2765-11eb-80f1-b722ace2a27f.png)
![image](https://user-images.githubusercontent.com/34653853/99190145-3340d880-2765-11eb-9838-5d15b5953c9f.png)

### Device:
RG351P on 351ELEC 1.01 32bits.

### Additional info:
Everything works when I replace the 32bits SYSTEM image with the 64bits one.

**Comment by fewtarius** [comment]
I was able to reproduce this, and it's fixed in git.  If it's not working properly in the 1.0.2 test builds we'll re-open.
