### ISSUE TITLE
Dreamcast emulator crashes when loading game save

### ISSUE THREAD

**Issue by xjanx83** [fewtarius/351ELEC#82]
Always happens to me  when loading the safe game (not vmu safe game) in hydro thunder.

Apart from Dreamcast no issues thought :)

**Comment by VallicMagnus** [comment]
I've also noticed some crashes in different Dreamcast games. Sonic adventure in the chao gardens just recently and some others. I'm thinking that some of this is just due to the emulator although I've not run flycast on anything but this device so I cannot make any assertions.

**Comment by fewtarius** [comment]
Please use discord for questions, the issue tracker is for bugs and feature requests and requires the use of bug/feature templates.
