### ISSUE TITLE
Is there anyway to map more functions to other buttons on the Mplayer application?

### ISSUE THREAD

**Issue by charlox612** [fewtarius/351ELEC#83]
The reason I ask this is because I think I could actually enjoy this feature more if it had a few more functions that would improve the experience a tad bit more. I was wondering if there was a way to map other functions like toggling audio/subtitles, and maybe be able to skip by chapters instead of going forward by seconds.

**Comment by fewtarius** [comment]
Yes, but those controls are hard coded in the jslisten function.  If you have a list of controls you'd like to see added, we can take a look.  Please use the feature request template for that.
