### ISSUE TITLE
How to get back to the old hotkeys (that we had in 1.0.5)?

### ISSUE THREAD

**Issue by denisvmedia** [fewtarius/351ELEC#88]
I find problematic to use new RetroArch hotkeys. The major problem is selecting a save slot. Pressing select and choosing top or down is a very unlucky combination that's hard to do by one hand on the joypad we have in our devices.

**Comment by fewtarius** [comment]
The community voted to adopt a standard set of hotkeys.  You can re-assign them from the RetroArch menu system, if you run into trouble setting them with a game loaded start RetroArch from the settings menu.

**Comment by denisvmedia** [comment]
Yeah, but which community? Each device has different button placement. If you have a select button, it's convenient to use it. But if you have a select button on the right, it's not good option...

**Comment by fewtarius** [comment]
The 351ELEC community, we held a vote in our Discord in December.

**Comment by denisvmedia** [comment]
I see. Thanks for the info. It's very strange. Maybe my fingers are wrong, but pressing select and up is extremely inconvenient. Will revert the config just for myself.
