### ISSUE TITLE
Can't find any wifi networks??

### ISSUE THREAD

**Issue by abelogan** [fewtarius/351ELEC#9]
I just got finished flashing the custom firmware, copying all my games back to my SD card, and I thought I'd be ready to go, but when I try to connect to my wifi network, I can enable wifi, but when I scan for networks, it doesn't find any, and I get a "NO NETWORKS FOUND" message.  I tried manually entering my network name and password, and still nothing.  My wifi was working without any issues on the stock firmware.  Am I missing something here?  Why would I not be able to connect to (or even detect) any wifi networks after flashing the CFW??

**Comment by fewtarius** [comment]
Closing, issues are not for technical support.  If you have found a bug, open a bug using the proper template and provide as much detail as possible.
