### ISSUE TITLE
NEC - PC Engine SuperGrafx (Beetle SuperGrafx

### ISSUE THREAD

**Issue by bllpla** [fewtarius/351ELEC#91]
Hi all, is possible to implement the core of NEC - PC Engine SuperGrafx (Beetle SuperGrafx ?
I like to tri it.

The core NEC - PC Engine / CD (Beetle PCE FAST) is very good but the game "Sylphia"
don't work

thanks in advance

**Comment by ciaskohansen** [comment]
Sylphia is working fine with PCE Fast

**Comment by bllpla** [comment]
yes, right, is my bad, i try USA syscard, the correct is JAP.  :(

Thanks for all, and thanks for the great job whit 351ELEC

**Comment by fewtarius** [comment]
Glad it was worked out, closing.
