### ISSUE TITLE
copy from otg cable to memory card

### ISSUE THREAD

**Issue by fabinhojcr** [fewtarius/351ELEC#95]
would it be possible to add the option to copy files from a USB stick connected to the otg cable to the memory card? to be able to add new roms without having to remove the memory card.

**Comment by fewtarius** [comment]
Please use discord for support, and templates when opening bug reports and feature requests.

351ELEC already supports this using the built in file manager.

**Comment by fabinhojcr** [comment]
I can't find my flash drive in the file manager
