### ISSUE TITLE
Not working uae4arm

### ISSUE THREAD

**Issue by overburner** [fewtarius/351ELEC#98]
### Describe the bug
Libretro Core - uae4arm not working or it's missing.

### To Reproduce
1. Go to: Main menu -> Game settings -> Per system advanced configuration
2. Select: Commodore Amiga -> Emulator -> libretro/uae4arm
3. Try to start any Amiga game from Emulationstation and see default error screen.

### Expected behavior
Game should start.

### Device (please complete the following information):
 - 351ELEC v1.0.8 (Latest release)
### Additional context
It's seems, uae4arm core is missing both in the retroarch UI and in the /usr/lib/libretro

**Comment by fewtarius** [comment]
Looks like it may be 32bit only, I'll look into adding it.

**Comment by fewtarius** [comment]
This issue should be resolved in tonight's build.  Let me know if there's still an issue.

**Comment by overburner** [comment]
Still not working.

It looks like there is an extra check missing here: https://github.com/fewtarius/351ELEC/blob/3356f845d81ad9c85fb1b2298a4532440057c90f/packages/351elec/config/emuelec/scripts/emuelecRunEmu.sh#L346-L347
Something like this:
```
        if [[ "${PLATFORM}" == "psx" ]] || [[ "${PLATFORM}" == "n64" ]] || [[ "${PLATFORM}" == "amiga" ]]; then
                if [[ "${CORE}" == "pcsx_rearmed" ]] || [[ "${CORE}" == "parallel_n64" ]] || [[ "${CORE}" == "uae4arm" ]]; then
```

**Comment by fewtarius** [comment]
oof, you're right.  Forgot about that one.

**Comment by overburner** [comment]
In latest nightly (4a0ccc0) everything works perfectly 👍
